# Generated by Django 4.2 on 2025-03-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='modalidad',
            new_name='cobertura',
        ),
    ]
