# Generated by Django 4.2 on 2025-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('cliente', '0001_initial'),
        ('orden', '0002_rename_modalidad_orden_cobertura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo',
            field=models.CharField(default='ORD-2024-02324', editable=False, max_length=20, unique=True, verbose_name='Código de orden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='vehiculo.vehiculo', verbose_name='Vehiculo'),
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_vehiculos/')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='orden.orden')),
            ],
        ),
    ]
