# Generated by Django 4.2 on 2025-03-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('vehiculo', '0001_initial'),
        ('orden', '0003_alter_orden_options_remove_orden_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
        migrations.AlterField(
            model_name='imagenvehiculo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_vehiculo', to='orden.orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo'),
        ),
    ]
