# Generated by Django 4.2 on 2025-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_alter_orden_options_alter_imagenvehiculo_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenvehiculo',
            name='imagen',
            field=models.ImageField(upload_to='media/imagenes_vehiculos/'),
        ),
    ]
