# Generated by Django 4.2 on 2025-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_alter_imagenvehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenvehiculo',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_vehiculos/'),
        ),
    ]
