# Generated by Django 4.2 on 2025-03-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('vehiculo', '0001_initial'),
        ('orden', '0006_alter_imagenvehiculo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a cliente'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregar el vehiculo')], max_length=50, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'orden particular',
                'verbose_name_plural': 'ordenes particulares',
            },
        ),
        migrations.CreateModel(
            name='OrdenRecupero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Solicitar documentacion'), ('2', 'Enviar carpeta'), ('3', 'Recibir y enviar poder firmado'), ('4', 'Acordar turno'), ('5', 'Ingresar al taller'), ('6', 'Entregar el vehiculo')], max_length=50, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'orden recupero',
                'verbose_name_plural': 'ordenes recuperos',
            },
        ),
        migrations.CreateModel(
            name='OrdenRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a seguro'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregar el vehiculo')], max_length=50, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'orden riesgo',
                'verbose_name_plural': 'ordenes riesgo',
            },
        ),
        migrations.CreateModel(
            name='OrdenTerceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a cliente'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregar el vehiculo')], max_length=50, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'orden terceros',
                'verbose_name_plural': 'ordenes terceros',
            },
        ),
        migrations.RemoveField(
            model_name='imagenvehiculo',
            name='orden',
        ),
        migrations.AddField(
            model_name='imagenvehiculo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='imagenvehiculo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
