# Generated by Django 4.2 on 2025-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0009_alter_ordenparticular_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenrecupero',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
