# Generated by Django 4.2 on 2025-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0011_alter_ordenrecupero_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenparticular',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a cliente'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenrecupero',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Solicitar documentacion'), ('2', 'Enviar carpeta'), ('3', 'Recibir y enviar poder firmado'), ('4', 'Acordar turno'), ('5', 'Ingresar al taller'), ('6', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenriesgo',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a seguro'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenterceros',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'Enviar a cliente'), ('3', 'Acordar turno'), ('4', 'Ingresar al taller'), ('5', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
