# Generated by Django 4.2 on 2025-03-31 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orden', '0013_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('content_type', 'object_id')},
        ),
    ]
