# Generated by Django 4.2 on 2025-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0016_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='presupuestos/'),
        ),
    ]
