# Generated by Django 4.2 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0018_alter_ordenparticular_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenparticular',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Enviar presupuesto al cliente'), ('2', 'Acordar turno'), ('3', 'Esperando ingreso'), ('4', 'En el taller'), ('5', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenrecupero',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Solicitar documentacion'), ('2', 'Preparar poder'), ('3', 'Firmar y enviar poder'), ('4', 'Esperando respuesta'), ('5', 'Acordar turno'), ('6', 'En el taller'), ('7', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenriesgo',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Enviar presupuesto al seguro'), ('2', 'Esperando respuesta'), ('3', 'Acordar turno'), ('4', 'Espeando ingreso'), ('5', 'En el taller'), ('6', 'Entregado')], max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
