# Generated by Django 4.2 on 2025-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca del vehiculo')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo del vehiculo')),
                ('patente', models.CharField(max_length=200, verbose_name='Patente del vehiculo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
